version: '3'

services:
  spark-master:
    image: gettyimages/spark:2.2.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: spark-master
    networks:
      - scylla-net
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
      - 3001
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 3001:3001
    volumes:
      - ./data/spark-master:/tmp/data
      - ../scylladb-samples/streaming-into-scylla/target/scala-2.11:/jars

  spark-worker-1:
    image: gettyimages/spark:2.2.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: spark-worker-1
    networks:
      - scylla-net
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker-1:/tmp/data
      - ../scylladb-samples/streaming-into-scylla/connector-log4j.properties:/connector-log4j.properties
    depends_on:
      - spark-master

  spark-worker-2:
    image: gettyimages/spark:2.2.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: spark-worker-2
    networks:
      - scylla-net
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8082:8082
    volumes:
      - ./data/spark-worker-2:/tmp/data
      - ../scylladb-samples/streaming-into-scylla/connector-log4j.properties:/connector-log4j.properties
    depends_on:
      - spark-master


networks:
  scylla-net: